language: cpp
compiler:
 - gcc
 - clang 
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev qt4-qmake cppcheck
script: qmake FlareFramework.pro && make
after_script: cppcheck --verbose --enable=all --std=posix --std=c++11 --quiet `git ls-files src/\*.cpp`
